node('built-in'){
	parameters {
		password(name: "Password")
	}
	stage('Cleanup'){
		cleanWs()
	}
	stage('Git'){
		checkout scm
	}
	stage('Build'){
		withCredentials([string(credentialsId: 'OurSecret', variable: 'OurSecret')]) {
			echo "Use the password in a command: " + "${OurSecret}"
		}
		
		try{
			dotnetBuild project: env.WORKSPACE + '/working_with_jenkins/dotnet_code/ArlingtonThisWeek/ArlingtonThisWeek.sln', sdk: 'dotnet6'
		} catch(Exception e){
			echo e.toString()
			archiveArtifacts artifacts: '**/*.*', followSymlinks: false
			cleanWs()
		}
	}
	stage('Test'){
		dotnetTest project: '/var/jenkins_home/workspace/ArlingtonThisWeek-pipeline/working_with_jenkins/dotnet_code/ArlingtonThisWeek/ArlingtonThisWeek.Weather.Tests/bin/Debug/net6.0/ArlingtonThisWeek.Weather.Tests.dll', sdk: 'dotnet6'
	}
	stage('Artifact'){
		archiveArtifacts artifacts: '**/*.*', followSymlinks: false
	}
	stage('Cleanup'){
		cleanWs()
	}
}