node{
	parameters {
		password(name: "Password")
	}
	stage('Cleanup'){
		cleanWs()
	}
	stage('Git'){
		checkout scm
	}
	stage('Build'){
		withCredentials([string(credentialsId: 'OurSecret', variable: 'secretValue')]) {
			echo "Use the password in a command: " + ${secretValue}
		}
		
		try{
			dotnetBuild project: env.WORKSPACE + '/working_with_jenkins/dotnet_code/ArlingtonThisWeek/ArlingtonThisWeek.sln', sdk: 'dotnet6'
		} catch(Exception e){
			echo e.toString()
			archiveArtifacts artifacts: '**/*.*', followSymlinks: false
			cleanWs()
		}
	}
	stage('Test'){
		echo 'Run unit tests'
	}
	stage('Artifact'){
		archiveArtifacts artifacts: '**/*.*', followSymlinks: false
	}
	stage('Cleanup'){
		cleanWs()
	}
}